name: Upload to Nextcloud

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL that should be uploaded to NextCloud'
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: output
      - name: Upload files
        run: |
            curl \
              -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} \
              -T source_code.zip \
              -g ${{ secrets.NEXTCLOUD_URL }}/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/${{ inputs.url }}/

      - uses: geekyeggo/delete-artifact@v2
        if: always()
        with:
            name: output