name: Save to Nextcloud

on:
  push:
    branches:
      - dev

jobs:
  save-to-nextcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Archive source code
      run: |
        zip -r source_code.zip .
      working-directory: ${{ github.workspace }}

    - name: Save to Nextcloud
      uses: bumbummen99/nextcloud-uploader
      with:
        type: wget
        url: ${{ secrets.NEXTCLOUD_URL }}
        extract-audio: false